# Makefile for Microsoft Visual C++. #############
all: library models planets

testing: all
	make -C testing -f makefile.vc

library: lib
	make -C src -f makefile.vc

models: lib
	make -C model -f makefile.vc

planets: lib models
	make -C planet -f makefile.vc

lib:
	mkdir $lib

clean:
	make -C src -f makefile.vc clean
	make -C model -f makefile.vc clean
	make -C planet -f makefile.vc clean
	make -C testing -f makefile.vc clean
